version: '3'

services:

  otrecorder:
    image: owntracks/recorder
    ports:
      - 8083:8083
    volumes:
      - config:/config
      - store:/store
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - mosquitto-data:/mosquitto/data/
      - mosquitto-logs:/mosquitto/mosquitto.log
    configs:
      - mosquitto-conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

volumes:
  store:
  config:
  mosquitto-data
  mosquitto-logs
configs:
  mosquitto-conf
